spring:
  security:
    user:
      name: postman
      password: password
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: pass
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true

  datasource:
    url: jdbc:postgresql://localhost:5432/kbi_jwt_users
    username: postgres
    password: password!
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  h2:
    console:
      enabled: true
      path: /h2


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.example.employeeworld: INFO
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"

server:
  port: 8081


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970